/** A client generated by WSDOM that can execute messages received from Rust. */
export interface WSDOMClient {
	handleIncomingMessage(message: string): void | Promise<void>;
}

/** The sender-first constructor shape emitted by the WSDOM generator. */
export type WSDOMConstructor<Client extends WSDOMClient, Args extends readonly unknown[]> = new (
	sender: (message: string) => void,
	...args: Args
) => Client;

export type Awaitable<Value> = Value | Promise<Value>;

export type TransportStatus = "idle" | "connecting" | "open" | "reconnecting" | "closed";

export interface TransportLifecycle {
	onStatusChange?(status: TransportStatus): void;
	onError?(error: unknown): void;
}

export interface WebSocketTransportOptions {
	kind: "websocket";
	url: string | URL;
	protocols?: string | string[];
}

export interface LongPollTransportOptions {
	kind: "long-poll";
	url: string | URL;
	/** Delay after a successful poll response. Defaults to one second. */
	pollIntervalMs?: number;
	/** Override the browser fetch implementation, for example for tests. */
	fetch?: typeof fetch;
	/** Request options such as credentials or authorization headers. */
	requestInit?: Omit<RequestInit, "body" | "method" | "signal">;
}

export type TransportOptions = WebSocketTransportOptions | LongPollTransportOptions;

export interface ProtocolWrapperContext<InteractionRequest = unknown, InteractionResult = unknown> {
	/** Continue toward the physical transport, or emit a transport-bound control frame. */
	sendOutbound(message: string): Promise<void>;
	/** Continue toward the generated client, or emit a client-bound control frame. */
	sendInbound(message: string): Promise<void>;
	/** Ask the host application to satisfy an interactive protocol requirement. */
	interact(request: InteractionRequest): Promise<InteractionResult>;
}

/**
 * Async duplex middleware for protocol framing, handshakes, and control traffic.
 * A hook owns the message it receives and forwards it by calling the matching
 * context method. Omitting a hook forwards that direction unchanged.
 */
export interface ProtocolWrapper<InteractionRequest = unknown, InteractionResult = unknown> {
	start?(context: ProtocolWrapperContext<InteractionRequest, InteractionResult>): Awaitable<void>;
	stop?(context: ProtocolWrapperContext<InteractionRequest, InteractionResult>): Awaitable<void>;
	outbound?(
		message: string,
		context: ProtocolWrapperContext<InteractionRequest, InteractionResult>,
	): Awaitable<void>;
	inbound?(
		message: string,
		context: ProtocolWrapperContext<InteractionRequest, InteractionResult>,
	): Awaitable<void>;
}

export interface WSDOMTransportOptions<InteractionRequest = unknown, InteractionResult = unknown>
	extends TransportLifecycle {
	transport: TransportOptions;
	wrappers?: readonly ProtocolWrapper<InteractionRequest, InteractionResult>[];
	interact?: (request: InteractionRequest) => Awaitable<InteractionResult>;
}

/**
 * Connects a sender-first generated WSDOM client to either a WebSocket or a
 * JSON-array long-poll endpoint. Transport selection is always explicit.
 */
export class WSDOMTransport<
	Client extends WSDOMClient,
	Args extends readonly unknown[],
	InteractionRequest = unknown,
	InteractionResult = unknown,
> {
	public readonly client: Client;
	public status: TransportStatus = "idle";

	readonly #clientConstructor: WSDOMConstructor<Client, Args>;
	readonly #args: Args;
	readonly #options: WSDOMTransportOptions<InteractionRequest, InteractionResult>;
	readonly #wrappers: readonly ProtocolWrapper<InteractionRequest, InteractionResult>[];
	#outbound: string[] = [];
	#started = false;
	#closed = false;
	#wrappersStarted = false;
	#webSocket?: WebSocket;
	#pollAbort?: AbortController;
	#reconnectTimer?: ReturnType<typeof setTimeout>;
	#pollTimer?: ReturnType<typeof setTimeout>;
	#failures = 0;

	constructor(
		ClientConstructor: WSDOMConstructor<Client, Args>,
		args: Args,
		options: WSDOMTransportOptions<InteractionRequest, InteractionResult>,
	) {
		this.#clientConstructor = ClientConstructor;
		this.#args = args;
		this.#options = options;
		this.#wrappers = options.wrappers ?? [];
		this.client = new this.#clientConstructor((message) => this.#sendFromClient(message), ...this.#args);
	}

	/** Starts wrappers and the explicitly configured physical transport. */
	async start(): Promise<void> {
		if (this.#closed) throw new Error("A closed WSDOMTransport cannot be restarted");
		if (this.#started) return;
		this.#started = true;
		try {
			await this.#startWrappers();
			this.#connect();
		} catch (error) {
			this.#reportError(error);
			this.#started = false;
			throw error;
		}
	}

	/** Stops all activity, rejects future reconnects, and shuts wrappers down. */
	async close(): Promise<void> {
		if (this.#closed) return;
		this.#closed = true;
		this.#started = false;
		this.#clearTimers();
		this.#pollAbort?.abort();
		this.#pollAbort = undefined;
		const socket = this.#webSocket;
		this.#webSocket = undefined;
		if (socket && socket.readyState !== WebSocket.CLOSED) socket.close();
		this.#setStatus("closed");
		if (!this.#wrappersStarted) return;
		this.#wrappersStarted = false;
		for (let index = this.#wrappers.length - 1; index >= 0; index--) {
			try {
				await this.#wrappers[index].stop?.(this.#context(index));
			} catch (error) {
				this.#reportError(error);
			}
		}
	}

	#sendFromClient(message: string): void {
		void this.#dispatchOutbound(0, message).catch((error) => this.#reportError(error));
	}

	async #startWrappers(): Promise<void> {
		for (let index = 0; index < this.#wrappers.length; index++) {
			await this.#wrappers[index].start?.(this.#context(index));
		}
		this.#wrappersStarted = true;
	}

	#context(index: number): ProtocolWrapperContext<InteractionRequest, InteractionResult> {
		return {
			sendOutbound: (message) => this.#dispatchOutbound(index + 1, message),
			sendInbound: (message) => this.#dispatchInbound(index - 1, message),
			interact: async (request) => {
				if (!this.#options.interact) throw new Error("This protocol wrapper requires host interaction");
				return this.#options.interact(request);
			},
		};
	}

	async #dispatchOutbound(index: number, message: string): Promise<void> {
		if (index >= this.#wrappers.length) {
			this.#outbound.push(message);
			this.#flushWebSocket();
			return;
		}
		const wrapper = this.#wrappers[index];
		if (wrapper.outbound) await wrapper.outbound(message, this.#context(index));
		else await this.#dispatchOutbound(index + 1, message);
	}

	async #dispatchInbound(index: number, message: string): Promise<void> {
		if (index < 0) {
			await this.client.handleIncomingMessage(message);
			return;
		}
		const wrapper = this.#wrappers[index];
		if (wrapper.inbound) await wrapper.inbound(message, this.#context(index));
		else await this.#dispatchInbound(index - 1, message);
	}

	#connect(): void {
		if (this.#closed || !this.#started) return;
		this.#setStatus(this.#failures === 0 ? "connecting" : "reconnecting");
		if (this.#options.transport.kind === "websocket") this.#connectWebSocket();
		else this.#startPolling();
	}

	#connectWebSocket(): void {
		const { url, protocols } = this.#options.transport as WebSocketTransportOptions;
		let socket: WebSocket;
		try {
			socket = new WebSocket(url, protocols);
		} catch (error) {
			this.#handleFailure(error);
			return;
		}
		this.#webSocket = socket;
		socket.onopen = () => {
			if (socket !== this.#webSocket || this.#closed) return;
			this.#failures = 0;
			this.#setStatus("open");
			this.#flushWebSocket();
		};
		socket.onmessage = (event: MessageEvent<unknown>) => {
			if (socket !== this.#webSocket || typeof event.data !== "string") {
				if (typeof event.data !== "string") this.#reportError(new TypeError("WSDOM WebSocket frames must be strings"));
				return;
			}
			void this.#dispatchInbound(this.#wrappers.length - 1, event.data).catch((error) => this.#reportError(error));
		};
		socket.onerror = () => {
			if (socket === this.#webSocket) this.#handleFailure(new Error("WSDOM WebSocket errored"));
		};
		socket.onclose = () => {
			if (socket !== this.#webSocket) return;
			this.#webSocket = undefined;
			if (!this.#closed) this.#scheduleReconnect();
		};
	}

	#flushWebSocket(): void {
		const socket = this.#webSocket;
		if (!socket || socket.readyState !== WebSocket.OPEN) return;
		while (this.#outbound.length > 0) {
			const message = this.#outbound[0];
			try {
				socket.send(message);
				this.#outbound.shift();
			} catch (error) {
				this.#handleFailure(error);
				return;
			}
		}
	}

	#startPolling(): void {
		this.#setStatus("open");
		void this.#poll();
	}

	async #poll(): Promise<void> {
		if (this.#closed || !this.#started || this.#options.transport.kind !== "long-poll") return;
		const messages = this.#outbound.splice(0);
		const controller = new AbortController();
		this.#pollAbort = controller;
		try {
			const transport = this.#options.transport;
			const headers = new Headers(transport.requestInit?.headers);
			if (!headers.has("content-type")) headers.set("content-type", "application/json");
			const response = await (transport.fetch ?? globalThis.fetch)(transport.url, {
				...transport.requestInit,
				headers,
				method: "POST",
				body: JSON.stringify(messages),
				signal: controller.signal,
			});
			if (!response.ok) throw new Error(`WSDOM long-poll failed with HTTP ${response.status}`);
			const incoming: unknown = await response.json();
			if (!Array.isArray(incoming) || !incoming.every((message) => typeof message === "string")) {
				throw new TypeError("WSDOM long-poll responses must be JSON string arrays");
			}
			this.#failures = 0;
			for (const message of incoming) await this.#dispatchInbound(this.#wrappers.length - 1, message);
			this.#schedulePoll();
		} catch (error) {
			if (!controller.signal.aborted && !this.#closed) {
				this.#outbound.unshift(...messages);
				this.#handleFailure(error);
			}
		} finally {
			if (this.#pollAbort === controller) this.#pollAbort = undefined;
		}
	}

	#schedulePoll(): void {
		if (this.#closed || !this.#started || this.#options.transport.kind !== "long-poll") return;
		this.#pollTimer = setTimeout(() => void this.#poll(), this.#options.transport.pollIntervalMs ?? 1_000);
	}

	#handleFailure(error: unknown): void {
		this.#reportError(error);
		this.#scheduleReconnect();
	}

	#scheduleReconnect(): void {
		if (this.#closed || !this.#started || this.#reconnectTimer) return;
		this.#clearPollTimer();
		this.#pollAbort?.abort();
		this.#pollAbort = undefined;
		const socket = this.#webSocket;
		this.#webSocket = undefined;
		if (socket && socket.readyState !== WebSocket.CLOSED) socket.close();
		this.#setStatus("reconnecting");
		const delay = Math.min(250 * 2 ** this.#failures, 30_000);
		this.#failures++;
		this.#reconnectTimer = setTimeout(() => {
			this.#reconnectTimer = undefined;
			this.#connect();
		}, delay);
	}

	#clearPollTimer(): void {
		if (this.#pollTimer) clearTimeout(this.#pollTimer);
		this.#pollTimer = undefined;
	}

	#clearTimers(): void {
		if (this.#reconnectTimer) clearTimeout(this.#reconnectTimer);
		this.#reconnectTimer = undefined;
		this.#clearPollTimer();
	}

	#setStatus(status: TransportStatus): void {
		if (this.status === status) return;
		this.status = status;
		this.#options.onStatusChange?.(status);
	}

	#reportError(error: unknown): void {
		this.#options.onError?.(error);
	}
}
