[workspace]
members = [
	"wsdom-core/",
	"wsdom-macros/",
	"wsdom-macros-decl",
	"wsdom-ts-convert/",
	"wsdom/",
	"wsdom-javascript/",
	"wsdom-dom/",
	"examples/simple/",
	"examples/counter"
]
resolver = "2"
