[workspace]
members = [
	"wsdom-core/",
	"wsdom-macros/",
	"wsdom-macros-decl",
	"wsdom-ts-convert/",
	"wsdom/",
	"wsdom-javascript/",
	"wsdom-dom/",
	"integrations/wsdom-axum/", "wsdom-ts-parse",
	# "examples/hello/",
	# "examples/counter-manual/",
	# "examples/many-examples/"
]
resolver = "2"
