[workspace]
members = [
	"wsdom-core/",
	"wsdom-macros/",
	"wsdom-macros-decl",
	"wsdom-ts-convert/",
	"wsdom/",
	"wsdom-javascript/",
	"wsdom-dom/",
	"integrations/wsdom-axum/",
	"examples/simple/",
	"examples/counter/",
	"examples/counter-manual/",
	"examples/audio"
]
resolver = "2"
