[package]
name = "px-wsdom-gen"
version = "0.0.2"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/wishawa/wsdom"
description = "for the wsdom crate"

[dependencies]
hex = "0.4.3"
itertools = "0.14.0"
sha3 = "0.10.8"
