[package]
name = "wsdom-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
axum = "0.7"
wsdom-core = { path = "../../wsdom-core/" }
pin-project-lite = "0.2.13"